# Cleaning data for efficient mapping

In [2]:
import pandas as pd

In [16]:
pop = pd.read_csv('./data/Pop.csv')
prod = pd.read_csv('./data/GlobalFoodProduction.csv')
cal = pd.read_csv('./data/Cal.csv')

In [17]:
cal["x1"] = cal["x1"].apply(lambda x : x.lower())
pop["x1"] = pop["x1"].apply(lambda x : x.lower())
prod["Area"] = prod["Area"].apply(lambda x : x.lower())

In [18]:
# find rows of prod where Area contains china
prod[prod["Area"].str.contains("china")].Area.unique()
# change china to china, mainland
prod["Area"] = prod["Area"].apply(lambda x : x.replace("china, mainland", "china"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("china, hong kong sar", "hong kong"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("china, taiwan province of", "taiwan"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("china, macao sar", "macao"))

In [19]:
prod["Area"] = prod["Area"].apply(lambda x : x.replace("united states of america", "united states"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("russian federation", "russia"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("iran (islamic republic of)", "iran"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("lao people's democratic republic", "laos"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("republic of moldova", "moldova"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("venezuela (bolivarian republic of)", "venezuela"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("viet nam", "vietnam"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("brunei darussalam", "brunei"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("bolivia (plurinational state of)", "bolivia"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("united republic of tanzania", "tanzania"))
prod["Area"] = prod["Area"].apply(lambda x : x.replace("the former yugoslav republic of macedonia", "north macedonia"))

In [20]:
# find rows of prod where area contains
prod[prod["Area"].str.contains("world")].Area.unique()

array([], dtype=object)

In [21]:
cal["x1"] = cal["x1"].apply(lambda x : x.replace("united states of america", "united states"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("russian federation", "russia"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("iran (islamic republic of)", "iran"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("lao people's democratic republic", "laos"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("republic of moldova", "moldova"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("venezuela (bolivarian republic of)", "venezuela"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("viet nam", "vietnam"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("brunei darussalam", "brunei"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("bolivia (plurinational state of)", "bolivia"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("united republic of tanzania", "tanzania"))
cal["x1"] = cal["x1"].apply(lambda x : x.replace("the former yugoslav republic of macedonia", "north macedonia"))

In [22]:
# add a row to pop
pop = pop.append({"x1": "bahamas", "x2": 328289}, ignore_index=True)
pop = pop.append({"x1": "cape verde", "x2": 530549}, ignore_index=True)
pop = pop.append({"x1": "congo", "x2": 4574052}, ignore_index=True)
pop = pop.append({"x1": "cote d'ivoire", "x2": 23284095}, ignore_index=True)
pop = pop.append({"x1": "democratic republic of congo", "x2": 80747292}, ignore_index=True)
pop = pop.append({"x1": "gambia", "x2": 1913150}, ignore_index=True)
pop = pop.append({"x1": "macao", "x2": 586116}, ignore_index=True)
pop = pop.append({"x1": "micronesia", "x2": 105995}, ignore_index=True)
pop = pop.append({"x1": "myanmar", "x2": 53044168}, ignore_index=True)
pop = pop.append({"x1": "north korea", "x2": 24767164}, ignore_index=True)
pop = pop.append({"x1": "south korea", "x2": 50063069}, ignore_index=True)
pop = pop.append({"x1": "timor", "x2": 1172274}, ignore_index=True)

In [23]:
tot = cal.merge(pop, left_on="x1", right_on="x1", how="inner")

In [24]:
tot = tot.merge(prod, left_on="x1", right_on="Area", how="inner")

In [25]:
tot
#rename columns in tot from x1 to country, x2_x to population, x2_y to calories, and x2 to production
tot = tot.rename(columns={"x2_x": "fats", "x3": "proteins", "x4": "carbs", "x5": "fruits_and_veggies", "x2_y": "population"})
tot.drop("x1", axis=1, inplace=True)

In [30]:
tot

,fats,proteins,carbs,fruits_and_veggies,population,Area Abbreviation,Area Code,Area,Item Code,Item,...,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,41.30,107.38,37.996,330.4,31098161,AFG,2,afghanistan,2511,Wheat and products,...,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,41.30,107.38,37.996,330.4,31098161,AFG,2,afghanistan,2805,Rice (Milled Equivalent),...,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,41.30,107.38,37.996,330.4,31098161,AFG,2,afghanistan,2513,Barley and products,...,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,41.30,107.38,37.996,330.4,31098161,AFG,2,afghanistan,2513,Barley and products,...,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,41.30,107.38,37.996,330.4,31098161,AFG,2,afghanistan,2514,Maize and products,...,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20813,43.25,112.45,39.790,346.0,13107407,ZWE,181,zimbabwe,2948,Milk - Excluding Butter,...,373.0,357.0,359.0,356.0,341.0,385.0,418.0,457.0,426,451
20814,43.25,112.45,39.790,346.0,13107407,ZWE,181,zimbabwe,2960,"Fish, Seafood",...,5.0,4.0,9.0,6.0,9.0,5.0,15.0,15.0,15,15
20815,43.25,112.45,39.790,346.0,13107407,ZWE,181,zimbabwe,2960,"Fish, Seafood",...,18.0,14.0,17.0,14.0,15.0,18.0,29.0,40.0,40,40
20816,43.25,112.45,39.790,346.0,13107407,ZWE,181,zimbabwe,2961,"Aquatic Products, Other",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
20817,43.25,112.45,39.790,346.0,13107407,ZWE,181,zimbabwe,2928,Miscellaneous,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

In [ ]:
tot["x1"] = tot["x1"].apply(lambda x : x.lower())
tot
# show rows with missing values
tot[tot.isnull().any(axis=1)]

In [ ]:
tot.to_csv("./data/prod_with_pop_with_food.csv")